/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminOverviewMetrics {
  'activeCreators' : bigint,
  'contentStats' : contentStatistics,
  'totalUsers' : bigint,
  'salesData' : creatorSalesData,
}
export interface Affirmation {
  'id' : string,
  'creator' : Principal,
  'mood' : string,
  'text' : string,
  'timestamp' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ColoringPage {
  'id' : string,
  'theme' : string,
  'creator' : Principal,
  'difficulty' : string,
  'timestamp' : bigint,
  'image' : ExternalBlob,
}
export type ContentCategory = { 'lyrics' : null } |
  { 'audio' : null } |
  { 'poem' : null } |
  { 'quote' : null } |
  { 'artwork' : null } |
  { 'story' : null } |
  { 'coloringPage' : null };
export interface CreativeContent {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'contentBlob' : ExternalBlob,
  'preview' : string,
  'description' : string,
  'timestamp' : bigint,
  'category' : ContentCategory,
  'price' : bigint,
}
export interface CreativeStudioContent {
  'memes' : Array<Meme>,
  'affirmations' : Array<Affirmation>,
  'coloringPages' : Array<ColoringPage>,
}
export interface CreatorSummary {
  'creator' : Principal,
  'itemCount' : bigint,
  'totalSales' : bigint,
  'totalRevenue' : bigint,
}
export type DtfContentType = { 'freeDownload' : null } |
  { 'externalRedirect' : null } |
  { 'purchase' : null };
export interface DtfDesign {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'contentType' : DtfContentType,
  'externalLink' : [] | [string],
  'tags' : Array<string>,
  'previewThumbnail' : ExternalBlob,
  'timestamp' : bigint,
  'artist' : string,
  'price' : [] | [bigint],
}
export interface DtfDesignInput {
  'title' : string,
  'creator' : Principal,
  'contentType' : DtfContentType,
  'externalLink' : [] | [string],
  'tags' : Array<string>,
  'previewThumbnail' : ExternalBlob,
  'artist' : string,
  'price' : [] | [bigint],
}
export type ExternalBlob = Uint8Array;
export type KingsCollabContentType = { 'rap' : null } |
  { 'lyrics' : null } |
  { 'audio' : null } |
  { 'affirmation' : null } |
  { 'poem' : null };
export interface KingsCollabLegal {
  'attributionRequired' : boolean,
  'copyrightOwner' : Principal,
  'termsConsent' : boolean,
  'commercialUseAllowed' : boolean,
}
export interface KingsCollaborationHub {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'contentText' : [] | [string],
  'contentType' : KingsCollabContentType,
  'legalMetadata' : KingsCollabLegal,
  'description' : string,
  'audioBlob' : [] | [ExternalBlob],
  'collaborators' : Array<Principal>,
  'timestamp' : bigint,
}
export interface KingsCollaborationInput {
  'title' : string,
  'creator' : Principal,
  'contentText' : [] | [string],
  'contentType' : KingsCollabContentType,
  'legalMetadata' : KingsCollabLegal,
  'description' : string,
  'audioBlob' : [] | [ExternalBlob],
  'collaborators' : Array<Principal>,
}
export interface LicensingAgreement {
  'licensingTermsAccepted' : boolean,
  'contentId' : string,
  'creator' : Principal,
  'commercialUse' : boolean,
  'derivativeWorks' : { 'withAttribution' : null } |
    { 'none' : null } |
    { 'fullRemixRights' : null },
  'agreementTimestamp' : bigint,
  'royaltySplit' : Array<RoyaltySplit>,
  'redistributionRights' : { 'full' : null } |
    { 'none' : null } |
    { 'limited' : { 'usageTerms' : string } },
}
export interface Meme {
  'id' : string,
  'bottomCaption' : string,
  'creator' : Principal,
  'topCaption' : string,
  'font' : string,
  'backgroundImage' : ExternalBlob,
  'timestamp' : bigint,
}
export interface PurchaseRecord {
  'contentId' : string,
  'purchaseTime' : bigint,
  'buyer' : Principal,
  'sessionId' : string,
}
export interface RoyaltySplit { 'creator' : Principal, 'percentage' : bigint }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface coloringBookStats {
  'revenue' : bigint,
  'itemCount' : bigint,
  'salesCount' : bigint,
  'totalDownloads' : bigint,
}
export interface contentStatistics {
  'memes' : memeStats,
  'creativeWriting' : creativeWritingStats,
  'kingsCollabContent' : kingsCollabContentStats,
  'dtfPrints' : dtfPrintStats,
  'coloringBooks' : coloringBookStats,
}
export interface creativeWritingStats {
  'revenue' : bigint,
  'itemCount' : bigint,
  'salesCount' : bigint,
  'totalDownloads' : bigint,
}
export interface creatorSalesData {
  'creator' : Principal,
  'itemCount' : bigint,
  'totalSales' : bigint,
  'revenueBreakdown' : revenueBreakdownStats,
  'totalRevenue' : bigint,
}
export interface dtfPrintStats {
  'revenue' : bigint,
  'itemCount' : bigint,
  'salesCount' : bigint,
  'totalDownloads' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface kingsCollabContentStats {
  'revenue' : bigint,
  'itemCount' : bigint,
  'salesCount' : bigint,
  'totalDownloads' : bigint,
}
export interface memeStats {
  'revenue' : bigint,
  'itemCount' : bigint,
  'salesCount' : bigint,
  'totalDownloads' : bigint,
}
export interface revenueBreakdownStats {
  'dtfSales' : bigint,
  'coloringBookSales' : bigint,
  'audioSales' : bigint,
  'artSales' : bigint,
  'royaltyIncome' : bigint,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminUpdateLicensingAgreement' : ActorMethod<
    [LicensingAgreement],
    undefined
  >,
  'approveLicensingAgreement' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createKingsCollaboration' : ActorMethod<
    [KingsCollaborationInput],
    undefined
  >,
  'deleteAffirmation' : ActorMethod<[string], undefined>,
  'deleteColoringPage' : ActorMethod<[string], undefined>,
  'deleteContent' : ActorMethod<[string], undefined>,
  'deleteDtfDesign' : ActorMethod<[string], undefined>,
  'deleteKingsCollaboration' : ActorMethod<[string], undefined>,
  'deleteMeme' : ActorMethod<[string], undefined>,
  'downloadDtfDesign' : ActorMethod<[string], ExternalBlob>,
  'getAdminOverviewMetrics' : ActorMethod<[], AdminOverviewMetrics>,
  'getAffirmation' : ActorMethod<[string], [] | [Affirmation]>,
  'getAllAffirmations' : ActorMethod<[], Array<[string, Affirmation]>>,
  'getAllColoringPages' : ActorMethod<[], Array<[string, ColoringPage]>>,
  'getAllContent' : ActorMethod<[], Array<[string, CreativeContent]>>,
  'getAllDtfDesigns' : ActorMethod<[], Array<[string, DtfDesign]>>,
  'getAllDtfPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getAllKingsCollaborationContent' : ActorMethod<
    [],
    Array<[string, KingsCollaborationHub]>
  >,
  'getAllMemes' : ActorMethod<[], Array<[string, Meme]>>,
  'getAllPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerCreativeStudioContent' : ActorMethod<[], CreativeStudioContent>,
  'getCallerPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollabAsCollaborator' : ActorMethod<[], Array<KingsCollaborationHub>>,
  'getCollabByUser' : ActorMethod<[Principal], Array<KingsCollaborationHub>>,
  'getColoringPage' : ActorMethod<[string], [] | [ColoringPage]>,
  'getContentById' : ActorMethod<[string], CreativeContent>,
  'getContentLicensingAgreements' : ActorMethod<
    [string],
    {
      'pending' : [] | [LicensingAgreement],
      'published' : [] | [LicensingAgreement],
    }
  >,
  'getCreatorSummary' : ActorMethod<[Principal], CreatorSummary>,
  'getDtfDesignByTag' : ActorMethod<[string], Array<DtfDesign>>,
  'getDtfDesignsByArtist' : ActorMethod<[string], Array<DtfDesign>>,
  'getDtfDesignsByCreator' : ActorMethod<[Principal], Array<DtfDesign>>,
  'getDtfDesignsByType' : ActorMethod<[DtfContentType], Array<DtfDesign>>,
  'getDtfGallery' : ActorMethod<[], Array<DtfDesign>>,
  'getLicensingAgreement' : ActorMethod<[string], [] | [LicensingAgreement]>,
  'getMarketplaceGallery' : ActorMethod<[], Array<DtfDesign>>,
  'getMeme' : ActorMethod<[string], [] | [Meme]>,
  'getPendingLicensingRequests' : ActorMethod<
    [],
    Array<[string, LicensingAgreement]>
  >,
  'getPopularCreators' : ActorMethod<[], Array<CreatorSummary>>,
  'getPrivacyPolicy' : ActorMethod<[], [] | [string]>,
  'getRoyaltyAndLicensingSummary' : ActorMethod<
    [string],
    {
      'licensingTerms' : [] | [
        {
          'commercialUse' : boolean,
          'derivativeWorks' : { 'withAttribution' : null } |
            { 'none' : null } |
            { 'fullRemixRights' : null },
          'redistributionRights' : { 'full' : null } |
            { 'none' : null } |
            { 'limited' : { 'usageTerms' : string } },
        }
      ],
      'royaltySplits' : Array<RoyaltySplit>,
    }
  >,
  'getRoyaltySplits' : ActorMethod<[string], Array<RoyaltySplit>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserCreativeStudioContent' : ActorMethod<
    [Principal],
    CreativeStudioContent
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoicesOfKings' : ActorMethod<[], Array<KingsCollaborationHub>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'purchaseContent' : ActorMethod<[string, string], undefined>,
  'purchaseDtfDesign' : ActorMethod<[string, string], undefined>,
  'rejectLicensingAgreement' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveAffirmation' : ActorMethod<[Affirmation], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveColoringPage' : ActorMethod<[ColoringPage], undefined>,
  'saveMeme' : ActorMethod<[Meme], undefined>,
  'searchContent' : ActorMethod<
    [string, [] | [ContentCategory]],
    Array<CreativeContent>
  >,
  'searchDtfDesigns' : ActorMethod<[string], Array<DtfDesign>>,
  'searchKingsCollaboration' : ActorMethod<
    [string, [] | [KingsCollabContentType]],
    Array<KingsCollaborationHub>
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitLicensingAgreement' : ActorMethod<[LicensingAgreement], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAffirmation' : ActorMethod<[Affirmation], undefined>,
  'updateColoringPage' : ActorMethod<[ColoringPage], undefined>,
  'updateContent' : ActorMethod<[CreativeContent], undefined>,
  'updateDtfDesign' : ActorMethod<[DtfDesign], undefined>,
  'updateKingsCollaboration' : ActorMethod<[KingsCollaborationHub], undefined>,
  'updateLicensingAgreement' : ActorMethod<[LicensingAgreement], undefined>,
  'updateMeme' : ActorMethod<[Meme], undefined>,
  'updatePrivacyPolicy' : ActorMethod<[string], undefined>,
  'uploadContent' : ActorMethod<[CreativeContent], undefined>,
  'uploadDtfDesign' : ActorMethod<[DtfDesignInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];