/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoyaltySplit = IDL.Record({
  'creator' : IDL.Principal,
  'percentage' : IDL.Nat,
});
export const LicensingAgreement = IDL.Record({
  'licensingTermsAccepted' : IDL.Bool,
  'contentId' : IDL.Text,
  'creator' : IDL.Principal,
  'commercialUse' : IDL.Bool,
  'derivativeWorks' : IDL.Variant({
    'withAttribution' : IDL.Null,
    'none' : IDL.Null,
    'fullRemixRights' : IDL.Null,
  }),
  'agreementTimestamp' : IDL.Int,
  'royaltySplit' : IDL.Vec(RoyaltySplit),
  'redistributionRights' : IDL.Variant({
    'full' : IDL.Null,
    'none' : IDL.Null,
    'limited' : IDL.Record({ 'usageTerms' : IDL.Text }),
  }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const KingsCollabContentType = IDL.Variant({
  'rap' : IDL.Null,
  'lyrics' : IDL.Null,
  'audio' : IDL.Null,
  'affirmation' : IDL.Null,
  'poem' : IDL.Null,
});
export const KingsCollabLegal = IDL.Record({
  'attributionRequired' : IDL.Bool,
  'copyrightOwner' : IDL.Principal,
  'termsConsent' : IDL.Bool,
  'commercialUseAllowed' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const KingsCollaborationInput = IDL.Record({
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentText' : IDL.Opt(IDL.Text),
  'contentType' : KingsCollabContentType,
  'legalMetadata' : KingsCollabLegal,
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'collaborators' : IDL.Vec(IDL.Principal),
});
export const memeStats = IDL.Record({
  'revenue' : IDL.Nat,
  'itemCount' : IDL.Nat,
  'salesCount' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const creativeWritingStats = IDL.Record({
  'revenue' : IDL.Nat,
  'itemCount' : IDL.Nat,
  'salesCount' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const kingsCollabContentStats = IDL.Record({
  'revenue' : IDL.Nat,
  'itemCount' : IDL.Nat,
  'salesCount' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const dtfPrintStats = IDL.Record({
  'revenue' : IDL.Nat,
  'itemCount' : IDL.Nat,
  'salesCount' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const coloringBookStats = IDL.Record({
  'revenue' : IDL.Nat,
  'itemCount' : IDL.Nat,
  'salesCount' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const contentStatistics = IDL.Record({
  'memes' : memeStats,
  'creativeWriting' : creativeWritingStats,
  'kingsCollabContent' : kingsCollabContentStats,
  'dtfPrints' : dtfPrintStats,
  'coloringBooks' : coloringBookStats,
});
export const revenueBreakdownStats = IDL.Record({
  'dtfSales' : IDL.Nat,
  'coloringBookSales' : IDL.Nat,
  'audioSales' : IDL.Nat,
  'artSales' : IDL.Nat,
  'royaltyIncome' : IDL.Nat,
});
export const creatorSalesData = IDL.Record({
  'creator' : IDL.Principal,
  'itemCount' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'revenueBreakdown' : revenueBreakdownStats,
  'totalRevenue' : IDL.Nat,
});
export const AdminOverviewMetrics = IDL.Record({
  'activeCreators' : IDL.Nat,
  'contentStats' : contentStatistics,
  'totalUsers' : IDL.Nat,
  'salesData' : creatorSalesData,
});
export const Affirmation = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'mood' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ColoringPage = IDL.Record({
  'id' : IDL.Text,
  'theme' : IDL.Text,
  'creator' : IDL.Principal,
  'difficulty' : IDL.Text,
  'timestamp' : IDL.Int,
  'image' : ExternalBlob,
});
export const ContentCategory = IDL.Variant({
  'lyrics' : IDL.Null,
  'audio' : IDL.Null,
  'poem' : IDL.Null,
  'quote' : IDL.Null,
  'artwork' : IDL.Null,
  'story' : IDL.Null,
  'coloringPage' : IDL.Null,
});
export const CreativeContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentBlob' : ExternalBlob,
  'preview' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : ContentCategory,
  'price' : IDL.Nat,
});
export const DtfContentType = IDL.Variant({
  'freeDownload' : IDL.Null,
  'externalRedirect' : IDL.Null,
  'purchase' : IDL.Null,
});
export const DtfDesign = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentType' : DtfContentType,
  'externalLink' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'previewThumbnail' : ExternalBlob,
  'timestamp' : IDL.Int,
  'artist' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
});
export const PurchaseRecord = IDL.Record({
  'contentId' : IDL.Text,
  'purchaseTime' : IDL.Int,
  'buyer' : IDL.Principal,
  'sessionId' : IDL.Text,
});
export const KingsCollaborationHub = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentText' : IDL.Opt(IDL.Text),
  'contentType' : KingsCollabContentType,
  'legalMetadata' : KingsCollabLegal,
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'collaborators' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
});
export const Meme = IDL.Record({
  'id' : IDL.Text,
  'bottomCaption' : IDL.Text,
  'creator' : IDL.Principal,
  'topCaption' : IDL.Text,
  'font' : IDL.Text,
  'backgroundImage' : ExternalBlob,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
});
export const CreativeStudioContent = IDL.Record({
  'memes' : IDL.Vec(Meme),
  'affirmations' : IDL.Vec(Affirmation),
  'coloringPages' : IDL.Vec(ColoringPage),
});
export const CreatorSummary = IDL.Record({
  'creator' : IDL.Principal,
  'itemCount' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const DtfDesignInput = IDL.Record({
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentType' : DtfContentType,
  'externalLink' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'previewThumbnail' : ExternalBlob,
  'artist' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminUpdateLicensingAgreement' : IDL.Func([LicensingAgreement], [], []),
  'approveLicensingAgreement' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createKingsCollaboration' : IDL.Func([KingsCollaborationInput], [], []),
  'deleteAffirmation' : IDL.Func([IDL.Text], [], []),
  'deleteColoringPage' : IDL.Func([IDL.Text], [], []),
  'deleteContent' : IDL.Func([IDL.Text], [], []),
  'deleteDtfDesign' : IDL.Func([IDL.Text], [], []),
  'deleteKingsCollaboration' : IDL.Func([IDL.Text], [], []),
  'deleteMeme' : IDL.Func([IDL.Text], [], []),
  'downloadDtfDesign' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'getAdminOverviewMetrics' : IDL.Func([], [AdminOverviewMetrics], ['query']),
  'getAffirmation' : IDL.Func([IDL.Text], [IDL.Opt(Affirmation)], ['query']),
  'getAllAffirmations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Affirmation))],
      ['query'],
    ),
  'getAllColoringPages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ColoringPage))],
      ['query'],
    ),
  'getAllContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, CreativeContent))],
      ['query'],
    ),
  'getAllDtfDesigns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DtfDesign))],
      ['query'],
    ),
  'getAllDtfPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getAllKingsCollaborationContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, KingsCollaborationHub))],
      ['query'],
    ),
  'getAllMemes' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Meme))], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerCreativeStudioContent' : IDL.Func(
      [],
      [CreativeStudioContent],
      ['query'],
    ),
  'getCallerPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollabAsCollaborator' : IDL.Func(
      [],
      [IDL.Vec(KingsCollaborationHub)],
      ['query'],
    ),
  'getCollabByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(KingsCollaborationHub)],
      ['query'],
    ),
  'getColoringPage' : IDL.Func([IDL.Text], [IDL.Opt(ColoringPage)], ['query']),
  'getContentById' : IDL.Func([IDL.Text], [CreativeContent], ['query']),
  'getContentLicensingAgreements' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'pending' : IDL.Opt(LicensingAgreement),
          'published' : IDL.Opt(LicensingAgreement),
        }),
      ],
      ['query'],
    ),
  'getCreatorSummary' : IDL.Func([IDL.Principal], [CreatorSummary], ['query']),
  'getDtfDesignByTag' : IDL.Func([IDL.Text], [IDL.Vec(DtfDesign)], ['query']),
  'getDtfDesignsByArtist' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DtfDesign)],
      ['query'],
    ),
  'getDtfDesignsByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DtfDesign)],
      ['query'],
    ),
  'getDtfDesignsByType' : IDL.Func(
      [DtfContentType],
      [IDL.Vec(DtfDesign)],
      ['query'],
    ),
  'getDtfGallery' : IDL.Func([], [IDL.Vec(DtfDesign)], ['query']),
  'getLicensingAgreement' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LicensingAgreement)],
      ['query'],
    ),
  'getMarketplaceGallery' : IDL.Func([], [IDL.Vec(DtfDesign)], ['query']),
  'getMeme' : IDL.Func([IDL.Text], [IDL.Opt(Meme)], ['query']),
  'getPendingLicensingRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, LicensingAgreement))],
      ['query'],
    ),
  'getPopularCreators' : IDL.Func([], [IDL.Vec(CreatorSummary)], ['query']),
  'getPrivacyPolicy' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRoyaltyAndLicensingSummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'licensingTerms' : IDL.Opt(
            IDL.Record({
              'commercialUse' : IDL.Bool,
              'derivativeWorks' : IDL.Variant({
                'withAttribution' : IDL.Null,
                'none' : IDL.Null,
                'fullRemixRights' : IDL.Null,
              }),
              'redistributionRights' : IDL.Variant({
                'full' : IDL.Null,
                'none' : IDL.Null,
                'limited' : IDL.Record({ 'usageTerms' : IDL.Text }),
              }),
            })
          ),
          'royaltySplits' : IDL.Vec(RoyaltySplit),
        }),
      ],
      ['query'],
    ),
  'getRoyaltySplits' : IDL.Func([IDL.Text], [IDL.Vec(RoyaltySplit)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserCreativeStudioContent' : IDL.Func(
      [IDL.Principal],
      [CreativeStudioContent],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoicesOfKings' : IDL.Func(
      [],
      [IDL.Vec(KingsCollaborationHub)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'purchaseContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'purchaseDtfDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectLicensingAgreement' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveAffirmation' : IDL.Func([Affirmation], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveColoringPage' : IDL.Func([ColoringPage], [], []),
  'saveMeme' : IDL.Func([Meme], [], []),
  'searchContent' : IDL.Func(
      [IDL.Text, IDL.Opt(ContentCategory)],
      [IDL.Vec(CreativeContent)],
      ['query'],
    ),
  'searchDtfDesigns' : IDL.Func([IDL.Text], [IDL.Vec(DtfDesign)], ['query']),
  'searchKingsCollaboration' : IDL.Func(
      [IDL.Text, IDL.Opt(KingsCollabContentType)],
      [IDL.Vec(KingsCollaborationHub)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitLicensingAgreement' : IDL.Func([LicensingAgreement], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAffirmation' : IDL.Func([Affirmation], [], []),
  'updateColoringPage' : IDL.Func([ColoringPage], [], []),
  'updateContent' : IDL.Func([CreativeContent], [], []),
  'updateDtfDesign' : IDL.Func([DtfDesign], [], []),
  'updateKingsCollaboration' : IDL.Func([KingsCollaborationHub], [], []),
  'updateLicensingAgreement' : IDL.Func([LicensingAgreement], [], []),
  'updateMeme' : IDL.Func([Meme], [], []),
  'updatePrivacyPolicy' : IDL.Func([IDL.Text], [], []),
  'uploadContent' : IDL.Func([CreativeContent], [], []),
  'uploadDtfDesign' : IDL.Func([DtfDesignInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoyaltySplit = IDL.Record({
    'creator' : IDL.Principal,
    'percentage' : IDL.Nat,
  });
  const LicensingAgreement = IDL.Record({
    'licensingTermsAccepted' : IDL.Bool,
    'contentId' : IDL.Text,
    'creator' : IDL.Principal,
    'commercialUse' : IDL.Bool,
    'derivativeWorks' : IDL.Variant({
      'withAttribution' : IDL.Null,
      'none' : IDL.Null,
      'fullRemixRights' : IDL.Null,
    }),
    'agreementTimestamp' : IDL.Int,
    'royaltySplit' : IDL.Vec(RoyaltySplit),
    'redistributionRights' : IDL.Variant({
      'full' : IDL.Null,
      'none' : IDL.Null,
      'limited' : IDL.Record({ 'usageTerms' : IDL.Text }),
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const KingsCollabContentType = IDL.Variant({
    'rap' : IDL.Null,
    'lyrics' : IDL.Null,
    'audio' : IDL.Null,
    'affirmation' : IDL.Null,
    'poem' : IDL.Null,
  });
  const KingsCollabLegal = IDL.Record({
    'attributionRequired' : IDL.Bool,
    'copyrightOwner' : IDL.Principal,
    'termsConsent' : IDL.Bool,
    'commercialUseAllowed' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const KingsCollaborationInput = IDL.Record({
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentText' : IDL.Opt(IDL.Text),
    'contentType' : KingsCollabContentType,
    'legalMetadata' : KingsCollabLegal,
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'collaborators' : IDL.Vec(IDL.Principal),
  });
  const memeStats = IDL.Record({
    'revenue' : IDL.Nat,
    'itemCount' : IDL.Nat,
    'salesCount' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const creativeWritingStats = IDL.Record({
    'revenue' : IDL.Nat,
    'itemCount' : IDL.Nat,
    'salesCount' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const kingsCollabContentStats = IDL.Record({
    'revenue' : IDL.Nat,
    'itemCount' : IDL.Nat,
    'salesCount' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const dtfPrintStats = IDL.Record({
    'revenue' : IDL.Nat,
    'itemCount' : IDL.Nat,
    'salesCount' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const coloringBookStats = IDL.Record({
    'revenue' : IDL.Nat,
    'itemCount' : IDL.Nat,
    'salesCount' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const contentStatistics = IDL.Record({
    'memes' : memeStats,
    'creativeWriting' : creativeWritingStats,
    'kingsCollabContent' : kingsCollabContentStats,
    'dtfPrints' : dtfPrintStats,
    'coloringBooks' : coloringBookStats,
  });
  const revenueBreakdownStats = IDL.Record({
    'dtfSales' : IDL.Nat,
    'coloringBookSales' : IDL.Nat,
    'audioSales' : IDL.Nat,
    'artSales' : IDL.Nat,
    'royaltyIncome' : IDL.Nat,
  });
  const creatorSalesData = IDL.Record({
    'creator' : IDL.Principal,
    'itemCount' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'revenueBreakdown' : revenueBreakdownStats,
    'totalRevenue' : IDL.Nat,
  });
  const AdminOverviewMetrics = IDL.Record({
    'activeCreators' : IDL.Nat,
    'contentStats' : contentStatistics,
    'totalUsers' : IDL.Nat,
    'salesData' : creatorSalesData,
  });
  const Affirmation = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'mood' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ColoringPage = IDL.Record({
    'id' : IDL.Text,
    'theme' : IDL.Text,
    'creator' : IDL.Principal,
    'difficulty' : IDL.Text,
    'timestamp' : IDL.Int,
    'image' : ExternalBlob,
  });
  const ContentCategory = IDL.Variant({
    'lyrics' : IDL.Null,
    'audio' : IDL.Null,
    'poem' : IDL.Null,
    'quote' : IDL.Null,
    'artwork' : IDL.Null,
    'story' : IDL.Null,
    'coloringPage' : IDL.Null,
  });
  const CreativeContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentBlob' : ExternalBlob,
    'preview' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : ContentCategory,
    'price' : IDL.Nat,
  });
  const DtfContentType = IDL.Variant({
    'freeDownload' : IDL.Null,
    'externalRedirect' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const DtfDesign = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentType' : DtfContentType,
    'externalLink' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'previewThumbnail' : ExternalBlob,
    'timestamp' : IDL.Int,
    'artist' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
  });
  const PurchaseRecord = IDL.Record({
    'contentId' : IDL.Text,
    'purchaseTime' : IDL.Int,
    'buyer' : IDL.Principal,
    'sessionId' : IDL.Text,
  });
  const KingsCollaborationHub = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentText' : IDL.Opt(IDL.Text),
    'contentType' : KingsCollabContentType,
    'legalMetadata' : KingsCollabLegal,
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'collaborators' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
  });
  const Meme = IDL.Record({
    'id' : IDL.Text,
    'bottomCaption' : IDL.Text,
    'creator' : IDL.Principal,
    'topCaption' : IDL.Text,
    'font' : IDL.Text,
    'backgroundImage' : ExternalBlob,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
  });
  const CreativeStudioContent = IDL.Record({
    'memes' : IDL.Vec(Meme),
    'affirmations' : IDL.Vec(Affirmation),
    'coloringPages' : IDL.Vec(ColoringPage),
  });
  const CreatorSummary = IDL.Record({
    'creator' : IDL.Principal,
    'itemCount' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const DtfDesignInput = IDL.Record({
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentType' : DtfContentType,
    'externalLink' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'previewThumbnail' : ExternalBlob,
    'artist' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminUpdateLicensingAgreement' : IDL.Func([LicensingAgreement], [], []),
    'approveLicensingAgreement' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createKingsCollaboration' : IDL.Func([KingsCollaborationInput], [], []),
    'deleteAffirmation' : IDL.Func([IDL.Text], [], []),
    'deleteColoringPage' : IDL.Func([IDL.Text], [], []),
    'deleteContent' : IDL.Func([IDL.Text], [], []),
    'deleteDtfDesign' : IDL.Func([IDL.Text], [], []),
    'deleteKingsCollaboration' : IDL.Func([IDL.Text], [], []),
    'deleteMeme' : IDL.Func([IDL.Text], [], []),
    'downloadDtfDesign' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'getAdminOverviewMetrics' : IDL.Func([], [AdminOverviewMetrics], ['query']),
    'getAffirmation' : IDL.Func([IDL.Text], [IDL.Opt(Affirmation)], ['query']),
    'getAllAffirmations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Affirmation))],
        ['query'],
      ),
    'getAllColoringPages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ColoringPage))],
        ['query'],
      ),
    'getAllContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, CreativeContent))],
        ['query'],
      ),
    'getAllDtfDesigns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DtfDesign))],
        ['query'],
      ),
    'getAllDtfPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getAllKingsCollaborationContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, KingsCollaborationHub))],
        ['query'],
      ),
    'getAllMemes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Meme))],
        ['query'],
      ),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerCreativeStudioContent' : IDL.Func(
        [],
        [CreativeStudioContent],
        ['query'],
      ),
    'getCallerPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollabAsCollaborator' : IDL.Func(
        [],
        [IDL.Vec(KingsCollaborationHub)],
        ['query'],
      ),
    'getCollabByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(KingsCollaborationHub)],
        ['query'],
      ),
    'getColoringPage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ColoringPage)],
        ['query'],
      ),
    'getContentById' : IDL.Func([IDL.Text], [CreativeContent], ['query']),
    'getContentLicensingAgreements' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'pending' : IDL.Opt(LicensingAgreement),
            'published' : IDL.Opt(LicensingAgreement),
          }),
        ],
        ['query'],
      ),
    'getCreatorSummary' : IDL.Func(
        [IDL.Principal],
        [CreatorSummary],
        ['query'],
      ),
    'getDtfDesignByTag' : IDL.Func([IDL.Text], [IDL.Vec(DtfDesign)], ['query']),
    'getDtfDesignsByArtist' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DtfDesign)],
        ['query'],
      ),
    'getDtfDesignsByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DtfDesign)],
        ['query'],
      ),
    'getDtfDesignsByType' : IDL.Func(
        [DtfContentType],
        [IDL.Vec(DtfDesign)],
        ['query'],
      ),
    'getDtfGallery' : IDL.Func([], [IDL.Vec(DtfDesign)], ['query']),
    'getLicensingAgreement' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LicensingAgreement)],
        ['query'],
      ),
    'getMarketplaceGallery' : IDL.Func([], [IDL.Vec(DtfDesign)], ['query']),
    'getMeme' : IDL.Func([IDL.Text], [IDL.Opt(Meme)], ['query']),
    'getPendingLicensingRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, LicensingAgreement))],
        ['query'],
      ),
    'getPopularCreators' : IDL.Func([], [IDL.Vec(CreatorSummary)], ['query']),
    'getPrivacyPolicy' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getRoyaltyAndLicensingSummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'licensingTerms' : IDL.Opt(
              IDL.Record({
                'commercialUse' : IDL.Bool,
                'derivativeWorks' : IDL.Variant({
                  'withAttribution' : IDL.Null,
                  'none' : IDL.Null,
                  'fullRemixRights' : IDL.Null,
                }),
                'redistributionRights' : IDL.Variant({
                  'full' : IDL.Null,
                  'none' : IDL.Null,
                  'limited' : IDL.Record({ 'usageTerms' : IDL.Text }),
                }),
              })
            ),
            'royaltySplits' : IDL.Vec(RoyaltySplit),
          }),
        ],
        ['query'],
      ),
    'getRoyaltySplits' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RoyaltySplit)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserCreativeStudioContent' : IDL.Func(
        [IDL.Principal],
        [CreativeStudioContent],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoicesOfKings' : IDL.Func(
        [],
        [IDL.Vec(KingsCollaborationHub)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'purchaseContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'purchaseDtfDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectLicensingAgreement' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveAffirmation' : IDL.Func([Affirmation], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveColoringPage' : IDL.Func([ColoringPage], [], []),
    'saveMeme' : IDL.Func([Meme], [], []),
    'searchContent' : IDL.Func(
        [IDL.Text, IDL.Opt(ContentCategory)],
        [IDL.Vec(CreativeContent)],
        ['query'],
      ),
    'searchDtfDesigns' : IDL.Func([IDL.Text], [IDL.Vec(DtfDesign)], ['query']),
    'searchKingsCollaboration' : IDL.Func(
        [IDL.Text, IDL.Opt(KingsCollabContentType)],
        [IDL.Vec(KingsCollaborationHub)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitLicensingAgreement' : IDL.Func([LicensingAgreement], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAffirmation' : IDL.Func([Affirmation], [], []),
    'updateColoringPage' : IDL.Func([ColoringPage], [], []),
    'updateContent' : IDL.Func([CreativeContent], [], []),
    'updateDtfDesign' : IDL.Func([DtfDesign], [], []),
    'updateKingsCollaboration' : IDL.Func([KingsCollaborationHub], [], []),
    'updateLicensingAgreement' : IDL.Func([LicensingAgreement], [], []),
    'updateMeme' : IDL.Func([Meme], [], []),
    'updatePrivacyPolicy' : IDL.Func([IDL.Text], [], []),
    'uploadContent' : IDL.Func([CreativeContent], [], []),
    'uploadDtfDesign' : IDL.Func([DtfDesignInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };